# Settings for IMU node and IMU sensors
imu:
  update_rate: 100
  gyro:
    # Possible output data rates 95|190|380|760 Hz
    rate: 760
    # Possible output data ranges 250|500|2000 DPS
    range: 250
    # Enabling auto-range
    autorange: true
  accel:
    # Possible output data rates 1|10|25|50|100|200|400 Hz
    rate: 400
    # Possible output data ranges 2|4|8|16 g
    range: 2